export default async () => [
  {
    id: 'argentina',
    name: 'Argentina',
    source: 'Ministerio de Salud Argentina',
    historicCases: 5277525,
    historicDeaths: 115796,
    historicRecovered: 4630436,
    newCases: 1541,
    activeCases: 531293,
    newDeaths: 26,
    newRecovered: 0,
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/samerica/ar/64.png',
    flag: 'https://www.countryflags.io/ar/flat/64.png',
  },
  {
    id: 'bolivia',
    name: 'Bolivia',
    source: 'John Hopkins University',
    historicCases: 508166,
    historicDeaths: 18887,
    historicRecovered: 411830,
    newCases: 0,
    activeCases: 77449,
    newDeaths: 0,
    newRecovered: 0,
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/samerica/bo/64.png',
    flag: 'https://www.countryflags.io/bo/flat/64.png',
  },
  {
    id: 'brazil',
    name: 'Brazil',
    source: 'Ministério da Saúde Brasil',
    historicCases: 21697341,
    historicDeaths: 604679,
    historicRecovered: 18102750,
    newCases: 16853,
    activeCases: 2989912,
    newDeaths: 451,
    newRecovered: 0,
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/samerica/br/64.png',
    flag: 'https://www.countryflags.io/br/flat/64.png',
  },
];
